import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Navbar from './Components/Navbar/Navbar';

const font = Roboto({
  weight: '400', 
  style: 'normal', 
  display: 'swap', 
  subsets: ['latin'], 
});

export const metadata: Metadata = {
  title: 'Test Submission',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body 
      className={font.className}>
        <Navbar />
        
        {children}
        </body>
    </html>
  )
}